package com.wangym.lombok.job;

import org.springframework.core.Ordered;
import org.springframework.util.FileCopyUtils;

import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

/**
 * @author wangym
 * @version 创建时间：2018年11月23日 上午11:23:37
 */
public abstract class JavaJob extends AbstractJob implements Ordered {

    public JavaJob() {
        super(".java");
    }

    @Override
    public void exec(File file) throws IOException {
        byte[] bytes = FileCopyUtils.copyToByteArray(file);
        String code = new String(bytes, "utf-8");
        try {
            precheck(code);
        } catch (IllegalAccessError e) {
            //ignore
            return;
        }
        handle(file);
    }
    private void precheck(String code){
        List<String> keys = Arrays.asList("Autogenerated by Thrift Compiler","do not edit this file");
        for (String key : keys) {
            if(code.contains(key)) {
                throw new IllegalAccessError("当前文件不进行修正");
            }
        }

    }

    @Override
    public int getOrder() {
        return 0;
    }

    abstract void handle(File file) throws IOException;

}
